spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/morninggrind
spring.datasource.username=morninggrind
spring.datasource.password=REMOVED_SECRET
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true